### ISSUE TITLE
Find and replace setup is quadruplicated in the context menu

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16462]
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1474.sha.723e992378842828924aea037a6d2da975cd8da4 (64 Bit)

This menu entry is buggy (cf #16460). But it is also defined many times.

<img width="387" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/fa081ce9-34d5-4b57-8709-b98745884acd">

<img width="385" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/eeb1824c-b5ff-45f8-b725-be3ad5e8b848">

<img width="393" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/32592e49-16ca-4846-af7d-79dfedd0d236">

<img width="433" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/95cdbc9e-ea86-4846-b866-77474943cb11">

**Comment by jecisc** [comment]
I have the impression this is now fixed. Can you confirm?

**Comment by estebanlm** [comment]
yep, I do not see other then "Find and replace setUp"

**Comment by matburnx** [comment]
Rechecked and it's also fixed for me.

**Comment by guillep** [comment]
No, it's not fixed. It happens to us in build 1487. We are making a PR.

**Comment by guillep** [comment]
This menu entry only appears when selecting a setUp methods.
