### ISSUE TITLE
"Basic inspect it" causes system error

### ISSUE THREAD

**Issue by marsell** [guillep/pharo-core#5579]
![exception](https://user-images.githubusercontent.com/144988/73139814-449fe380-4072-11ea-9b22-b1e7c1f120ce.png)

Replication steps:

1. open Playground
2. type "1"
3. Right-click on 1 and select "Basic Inspect it"

This affects Pharo-8.0.0+build.1122.sha.bbcdf9770748d12e2c1b84f168f0232e4f918d20 (64 Bit), running on Windows.

**Comment by JanBliznicenko** [comment]
I confirm the issue. The main problem is the deprecation warning which should not happen and should be fixed in Pharo 8.
Because of bug fixed since build 1124 (current main image in Pharo Launcher), emergency evaluator opens instead of warning window (see closed issue #5545 ).

This is the real, still existing, problem that needs to be fixed:
![2020-01-26](https://user-images.githubusercontent.com/9571633/73140323-f55cb180-4077-11ea-80dd-a66d733d808a.png)

**Comment by estebanlm** [comment]
this should be fixed now (since it was the same problem as the Warning stuff)

**Comment by JanBliznicenko** [comment]
@estebanlm Well, the warning no longer opens emergency evaluator instead of debugger window, but the deprecation warning should not happen at all when user tries to use "Basic inspect it". That is the problem that still needs to be fixed (is not fixed in build 1124).

**Comment by MarcusDenker** [comment]
I tried to fix this, but after doing it it turns out there are many many more things not working
(e.g #doItReceiver:  is depurated, too).

I suggest we should remove the menu entry as this tool is completely broken and not used...

**Comment by JanBliznicenko** [comment]
I agree - we don't need the tool to work, just remove it so that nobody would accidentaly try to use it and get these errors as a result.

**Comment by MarcusDenker** [comment]
fixed as https://github.com/pharo-spec/NewTools/pull/431
