### ISSUE TITLE
implementors and senders browsing broken in the debugger

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7616]
**Describe the bug**
The debugger strangely uses different broken way how to detect selector for browsing of implementors and senders using keyboard shortcut (for multipart keyword messages)

**To Reproduce**
1. evaluate `self halt` to open a debugger
2. got to `SpCodeSelectionCommand>>#evaluateSelectionAndDo:`
3. add the bottom od the method, there is a call:
```smalltalk
^ self 
		evaluate: selection 
		andDo: aBlock
```
4. place the cursor in the middle of `evaluate:` part and press `Ctrl+M` (or platform equivalent)
5. it will browse implementors of `selection`

If you do the same in the same method in Calypso, it works correctly and browses implementors of `evaluate:andDo:`

**Comment by Ducasse** [comment]
Yes we know. Guille was working on fixing it.

**Comment by MarcusDenker** [comment]
We now merged https://github.com/pharo-project/pharo/pull/7660

But I think this now needs an additional change so this will be used in Spec2

**Comment by Ducasse** [comment]
the hot fix 
```
SpCodePresenter >> selectedSelector
	^ (CNSelectorExtractor new extractSelectorFromSelection: self selectedTextOrLine)
```

**Comment by pavel-krivanek** [comment]
thanks!

**Comment by pavel-krivanek** [comment]
The hot-fix does not seem to work, at least in the case described above, it still shows only implementors of `evaluate:`

**Comment by maxwills** [comment]
I am working on this. Will resume after lunch.

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-project/pharo/pull/8462
